version: "3"
services:
    laravel-app:
        build: .
        container_name: laravel-app-lotto
        ports:
            - "8082:80"
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:latest
        container_name: mariadb-lotto
        environment:
            MYSQL_ROOT_PASSWORD: lotto
            MYSQL_DATABASE: lotto
            MYSQL_USER: lotto
            MYSQL_PASSWORD: lotto
        volumes:
            - mariadb_data:/var/lib/mysql

volumes:
    mariadb_data:
